### ISSUE TITLE
world conversion error

### ISSUE THREAD

**Issue by amazingchocolat** [HiveGamesOSS/Chunker#70] opened 2024-10-10 14:30 UTC
### Chunker Version

1.2.0-main-4ae23ae

### Input World Version

bedrock 1.21.3

### Output World Version

java 1.19.4

### Platform / Operating System

windows 11

### Issue Description

world conversion always fails. error codes as listed 
4b042885-a256-4663-a53c-09e9bb72ea83
b73a5007-4968-46c7-9820-b0a0eb6a278a

**Comment by FormallyMyles** [comment] 2024-10-10 15:01
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.

**Comment by amazingchocolat** [comment] 2024-10-11 00:40
[main.log](https://github.com/user-attachments/files/17335881/main.log)
[kgc1ZMp3DAA=.zip](https://github.com/user-attachments/files/17335883/kgc1ZMp3DAA.zip)

**Comment by FormallyMyles** [comment] 2024-10-11 09:00
Thanks! We'll get this fixed in the next release.

**Comment by amazingchocolat** [comment] 2024-10-11 13:32
when will that be also what was the issue?

**Comment by FormallyMyles** [comment] 2024-10-11 14:16
I'm unable to say an exact timeframe but it'll be hopefully within the next week, you can downgrade to the previous version `1.1.2` and it should also work. The issue is to do with the sign translation not loading required files properly which is just in `1.2.0`.

**Comment by FormallyMyles** [comment] 2024-10-20 08:56
Closing as we'll use https://github.com/HiveGamesOSS/Chunker/issues/71 for tracking this issue.

**Closed by FormallyMyles** 2024-10-20 08:56 UTC
Labels: Conversion Bug
