### ISSUE TITLE
World Conversion Issue....

### ISSUE THREAD

**Issue by Jay19911** [HiveGamesOSS/Chunker#75] opened 2024-10-13 06:40 UTC
### Chunker Version

1.2.0-main-4ae23ae

### Input World Version

Bedrock 1.19.50

### Output World Version

Bedrock 1.21.30

### Platform / Operating System

win32-x64-10.0.22621

### Issue Description

Error Chunker Displayed: A fatal error occurred during conversion.

Error identifier: adbb8dec-2a7b-444b-ba92-100377291cea

**Comment by FormallyMyles** [comment] 2024-10-13 09:09
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.

**Comment by FormallyMyles** [comment] 2024-10-20 08:59
This seems like a duplicate of https://github.com/HiveGamesOSS/Chunker/issues/71, we'll update that issue when a fix is released.

**Closed by FormallyMyles** 2024-10-20 08:59 UTC
Labels: Conversion Bug
