### ISSUE TITLE
A fatal error occured while converting a world

### ISSUE THREAD

**Issue by DominikP78** [HiveGamesOSS/Chunker#85] opened 2024-10-17 16:15 UTC
### Chunker Version

1.2.0 windows

### Input World Version

Bedrock 1.20.70

### Output World Version

Java 1.21.1, I also tried Java 1.20.6

### Platform / Operating System

Windows 11 64 Bit

### Issue Description

Dear Chunker Team,
When I start converting my world, it convert normally until it reaches 4.28%. Then it stops for a while and later goes to 8.something%. After a while it gives me and Error: A fatal error occurred during conversion.
If this error continues please report it to us via our [GitHub issues]
Error identifier: 9a06a9a6-2b38-4977-af50-18c5e9325dc7
Could you please help me?
Best regards!
Dominik

**Comment by DominikP78** [comment] 2024-10-17 16:15
![grafik](https://github.com/user-attachments/assets/5f0d2ff9-86cc-4cbc-bd61-e7b09595d4c5)
![636829723898798601](https://github.com/user-attachments/assets/9c8592d4-933b-40de-b5b7-56953b4476e1)
I forgot to add the files, sorry.

**Comment by DominikP78** [comment] 2024-10-17 16:20
Sorry for another message but the file that should be the world turned into the fabric logo here on GitHub. Here's the file as a download: https://uploadnow.io/f/gK7rxck

**Comment by FormallyMyles** [comment] 2024-10-20 09:01
This seems like a duplicate of https://github.com/HiveGamesOSS/Chunker/issues/71, we'll update that issue when a fix is released.

**Closed by FormallyMyles** 2024-10-20 09:01 UTC
Labels: Conversion Bug

**Comment by DominikP78** [comment] 2024-10-20 09:18
Ok sorry I didn't see that that issue already existed. Thank you for pointing that out to me!
