### ISSUE TITLE
Oops, Failed to convert world

### ISSUE THREAD

**Issue by CitricLocket** [HiveGamesOSS/Chunker#89] opened 2024-10-19 12:57 UTC
### Chunker Version

1.2.0-main-4ae23ae

### Input World Version

Bedrock 1.21.30

### Output World Version

Java 1.21.1

### Platform / Operating System

win32-x64-10.0.22631

### Issue Description

Error Chunker Displayed: A fatal error occurred during conversion.
Error identifier: 3e9bda0f-712f-4839-b4d5-bf4e9448a15a

**Comment by FormallyMyles** [comment] 2024-10-20 09:03
This seems like a duplicate of https://github.com/HiveGamesOSS/Chunker/issues/71, we'll update that issue when a fix is released.

**Closed by FormallyMyles** 2024-10-20 09:03 UTC
Labels: Conversion Bug
