### ISSUE TITLE
Error identifier: a5a8bdba-9ac5-4ec3-85c6-f4f1de528ed7, occured during conversion process 3 separate times

### ISSUE THREAD

**Issue by RumpyScrumpy** [HiveGamesOSS/Chunker#86] opened 2024-10-18 23:36 UTC
### Chunker Version

1.2.0-main-4ae23ae

### Input World Version

Bedrock 1.21.30

### Output World Version

Java 1.21.0

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Chunker Displayed: A fatal error occurred during conversion.

**Comment by FormallyMyles** [comment] 2024-10-20 09:02
This seems like a duplicate of https://github.com/HiveGamesOSS/Chunker/issues/71, we'll update that issue when a fix is released.

**Closed by FormallyMyles** 2024-10-20 09:02 UTC
Labels: Conversion Bug
