### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pgrd1** [HiveGamesOSS/Chunker#72] opened 2024-10-12 03:17 UTC
### Chunker Version

1.2.0-main-4ae23ae

### Input World Version

Bedrock 1.21.30

### Output World Version

N/A

### Platform / Operating System

win32-x64-10.0.22631

### Issue Description

Error Chunker Displayed: A fatal error occurred during conversion.

**Comment by FormallyMyles** [comment] 2024-10-13 09:09
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.

**Comment by FormallyMyles** [comment] 2024-10-20 08:57
I didn't get a response but I'll assume this is a duplicate of https://github.com/HiveGamesOSS/Chunker/issues/71 given it's from Bedrock.

**Closed by FormallyMyles** 2024-10-20 08:57 UTC
Labels: Conversion Bug
