### ISSUE TITLE
Error Identifier 1009e1ec-aeaa-456a-a178-35f06990fb40

### ISSUE THREAD

**Issue by YoXpertguyZ** [HiveGamesOSS/Chunker#82] opened 2024-10-16 16:44 UTC
### Chunker Version

1.2.0-main-4ae23ae

### Input World Version

Bedrock 1.21.30

### Output World Version

Java 1.21.0

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Chunker Displayed: A fatal error occurred during conversion.
1009e1ec-aeaa-456a-a178-35f06990fb40
[main.log](https://github.com/user-attachments/files/17399799/main.log)

**Comment by FormallyMyles** [comment] 2024-10-20 08:58
This seems like a duplicate of https://github.com/HiveGamesOSS/Chunker/issues/71, we'll update that issue when a fix is released.

**Closed by FormallyMyles** 2024-10-20 08:58 UTC
Labels: Conversion Bug
