### ISSUE TITLE
Error Converting

### ISSUE THREAD

**Issue by TheOneMightyArc** [HiveGamesOSS/Chunker#87] opened 2024-10-19 00:38 UTC
### Chunker Version

1.2.0-main-4ae23ae

### Input World Version

Bedrock 1.21.30

### Output World Version

Java 1.20.1

### Platform / Operating System

win32-x64-10.0.22621

### Issue Description

Error Chunker Displayed: A fatal error occurred during conversion.
![image](https://github.com/user-attachments/assets/d6e7c710-1fb7-45b9-91f5-8c572c75db15)

**Comment by FormallyMyles** [comment] 2024-10-20 09:03
This seems like a duplicate of https://github.com/HiveGamesOSS/Chunker/issues/71, we'll update that issue when a fix is released.

**Closed by FormallyMyles** 2024-10-20 09:03 UTC
Labels: Conversion Bug
